### ISSUE TITLE
Private OCI chart repositories not working

### ISSUE THREAD

**Issue by eloo-abi** [allenporter/flux-local#717]
Hi,

i'm trying to get flux-local running but i'm struggling with a private OCI helm chart repo (Harbor).

I guess the issue is that the registry-config parameter is set to `/dev/null`
https://github.com/allenporter/flux-local/blob/main/flux_local/helm.py#L163

This also seems to block the possibility to change it using the env variable.
So i'm curious what the reason is why the registry-config is set to `/dev/null`?

Maybe this could be removed or at least made be configurable so its possible to use private OCI registries?

Thanks

**Comment by allenporter** [comment]
Hi, definitely open to being flexible here. The main reason this is disabled is so that helm only looks at things defined in the repository. I am not super familiar with the details of OCI other than basics to make it work, nor how to configure private repos. Happy to talk through a solution (one of the options you propose may be the right one) though may need some help understanding a little more what the workflow is supposed to look like.  Can you give me a little more background on how you set this up and specify private oci helm chart repos in practice?

There is also discussion in https://github.com/allenporter/flux-local/issues/301 so wondering if a single approach solves both.

**Comment by allenporter** [comment]
I've added a `--repository-config` in 5.4.0. Will mark as closed but repoen if there is a problem using it.

**Comment by eloo-abi** [comment]
@allenporter i've just tested the lastest version and it works now for our setup with private OCI chart repos

Thanks!
